### ISSUE TITLE
The judge should automatically interpret "\r\n" (Windows newline) as "\n"

### ISSUE THREAD

**Issue by phizaz** [nattee/cafe-grader-web#22]
It is far too common that many `.in` files are generated by Windows, but being used for juding on Linux systems.

This causes a discrepancy of the newline characters (`\r\n` and `\n`) which is the reason why we have to force the users to use `input().strip()` in Python.

I think this should not be a burden for the users to take care of this. Instead either the testcase generator or the judge should be able to solve this discrepancy on the fly without the users knowing.

**Comment by nattee** [comment]
The import script now automatically remove \r\n and replace it with \n. This is done in nattee/cafe-grader-judge-scripts .
