### ISSUE TITLE
Problem Broken when all the dataset is deleted from the problem

### ISSUE THREAD

**Issue by noppakorn** [nattee/cafe-grader-web#39]
- When the last dataset is deleted from the problem, it will immediately show the error page
- After that, the problem is not visible on the problems page anymore
- If we try to access the problem page directly via the URL, it show an error message
- The stat page of the problem still works and show correct data and submissions
- The submission for this problem is not affected by this

**Comment by nattee** [comment]
Fixed in 39b62cc50a93416c9a817c417367faabe0c8f474
